# Generated by Django 5.1.4 on 2025-02-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkilimoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odk_id', models.CharField(max_length=50, unique=True)),
                ('odk_uuid', models.CharField(max_length=50, unique=True)),
                ('submission_time', models.DateTimeField()),
                ('submitted_by', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('sensitization_event', 'Sensitization Event'), ('training_event', 'Training Event')], max_length=50)),
                ('partner', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('title_full', models.TextField()),
                ('format', models.CharField(choices=[('paper', 'Paper'), ('digital', 'Digital')], max_length=20)),
                ('topics', models.TextField()),
                ('use_case', models.CharField(max_length=50)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('hasc1', models.CharField(max_length=10)),
                ('hasc2', models.CharField(max_length=10)),
                ('hasc1_name', models.CharField(max_length=50)),
                ('hasc2_name', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('event_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('enumerator_first_name', models.CharField(max_length=255)),
                ('enumerator_surname', models.CharField(max_length=255)),
                ('enumerator_gender', models.CharField(max_length=10)),
                ('enumerator_phone', models.CharField(max_length=20)),
                ('enumerator_organization', models.CharField(max_length=255)),
                ('enumerator_designation', models.CharField(max_length=100)),
                ('participantRepeat', models.JSONField(default=list)),
                ('participantRepeat_count', models.IntegerField(default=0)),
                ('complementary_services', models.CharField(blank=True, max_length=255, null=True)),
                ('input_types', models.CharField(blank=True, max_length=255, null=True)),
                ('input_organizations', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-event_date'],
                'indexes': [models.Index(fields=['partner'], name='dashboard_a_partner_7f4190_idx'), models.Index(fields=['event_date'], name='dashboard_a_event_d_78a8a8_idx'), models.Index(fields=['hasc1', 'hasc2'], name='dashboard_a_hasc1_15eb4a_idx')],
            },
        ),
    ]
