# Generated by Django 5.1.4 on 2025-02-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_sitesettings_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_profile_locked',
            field=models.BooleanField(default=False),
        ),
    ]
