# Generated by Django 5.1.4 on 2025-03-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_userprofile_is_profile_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akilimoevent',
            name='submitted_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
