# Generated by Django 5.1.4 on 2025-03-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_akilimoevent_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akilimoevent',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='akilimoevent',
            name='enumerator_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='akilimoevent',
            name='enumerator_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='akilimoevent',
            name='enumerator_gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='akilimoevent',
            name='enumerator_organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='akilimoevent',
            name='enumerator_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='akilimoevent',
            name='enumerator_surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='akilimoevent',
            name='event_type',
            field=models.CharField(choices=[('sensitization_event', 'Sensitization Event'), ('training_event', 'Training Event')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='akilimoevent',
            name='hasc1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='akilimoevent',
            name='hasc1_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='akilimoevent',
            name='hasc2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='akilimoevent',
            name='hasc2_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='akilimoevent',
            name='partner',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='akilimoevent',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='akilimoevent',
            name='use_case',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='akilimoevent',
            name='venue',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
