# Generated by Django 5.1.4 on 2025-03-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_akilimoevent_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akilimoevent',
            name='title_full',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='akilimoevent',
            name='topics',
            field=models.TextField(null=True),
        ),
    ]
