# Generated by Django 5.1.4 on 2025-03-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_akilimoevent_title_full_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akilimoevent',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='akilimoevent',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='akilimoevent',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
