# Generated by Django 5.1.4 on 2025-03-02 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_akilimoevent_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.partner'),
        ),
    ]
