# Generated by Django 5.1.4 on 2025-03-02 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_farmer_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, null=True)),
                ('lastname', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('own_phone', models.BooleanField(default=False)),
                ('crops', models.CharField(max_length=255, null=True)),
                ('crop_other', models.CharField(max_length=255, null=True)),
                ('farm_area', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('area_unit', models.CharField(choices=[('hectare', 'Hectare'), ('acre', 'Acre')], max_length=20)),
                ('cassava', models.BooleanField(default=False)),
                ('yam', models.BooleanField(default=False)),
                ('maize', models.BooleanField(default=False)),
                ('rice', models.BooleanField(default=False)),
                ('sorghum', models.BooleanField(default=False)),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.partner')),
            ],
        ),
    ]
