# Generated by Django 5.1.4 on 2025-03-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_farmerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerdata',
            name='index',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
