# Generated by Django 5.1.4 on 2025-03-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_farmerdata_partner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerdata',
            old_name='phone_number',
            new_name='phone_no',
        ),
    ]
