# Generated by Django 5.1.4 on 2025-03-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_rename_phone_number_farmerdata_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerdata',
            old_name='crop_other',
            new_name='crops_other',
        ),
    ]
