# Generated by Django 5.1.4 on 2025-03-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_rename_crop_other_farmerdata_crops_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerdata',
            name='area_unit',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
