# Generated by Django 5.1.4 on 2025-03-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_farmerdata_area_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerdata',
            name='cassava',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='farmerdata',
            name='maize',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='farmerdata',
            name='own_phone',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='farmerdata',
            name='rice',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='farmerdata',
            name='sorghum',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='farmerdata',
            name='yam',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
