# Generated by Django 5.1.4 on 2025-03-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_farmerdata_cassava_alter_farmerdata_maize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerdata',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
