# Generated by Django 5.1.4 on 2025-03-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_extensionagentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionagentdata',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
